import React from 'react';

/**
 * Displays the China Satellite investment section.
 * Details the rationale, opportunities, risks, and allocation approaches for this higher-risk part of the portfolio.
 *
 * @returns {JSX.Element} The ChinaSatelliteSection component.
 */
function ChinaSatelliteSection() {
    return (
        <section id="china-satellite" className="mb-16 scroll-mt-16" data-aos="fade-up">
             <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b pb-2 border-gray-300 dark:border-gray-600">China Satellite: Higher Growth Potential (€100 per month)</h2>
             <div className="grid md:grid-cols-2 gap-8 items-start">
                 <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow border border-gray-200 dark:border-gray-700"> <h3 className="text-xl font-semibold mb-4 text-rose-700 dark:text-rose-400">Opportunities vs. Risks</h3> <p className="text-sm text-gray-700 dark:text-gray-300 mb-6">This smaller allocation (€100/month) targets potentially higher returns via China's dynamic economy, but involves increased volatility and specific risks:</p> <div className="grid grid-cols-2 gap-x-6 gap-y-4 mb-6"> <div> <h4 className="font-semibold text-gray-800 dark:text-gray-200 mb-3 border-b border-green-200 dark:border-green-700 pb-1">Opportunities</h4> <div className="space-y-3"> <p className="flex items-start text-sm text-green-800 dark:text-green-300"><span className="lucide lucide-opps mt-0.5">&#xea2e;</span> <span>Growth Sectors (Tech, EV, AI)</span></p> <p className="flex items-start text-sm text-green-800 dark:text-green-300"><span className="lucide lucide-opps mt-0.5">&#xe9a8;</span> <span>Economic Scale & Development</span></p> <p className="flex items-start text-sm text-green-800 dark:text-green-300"><span className="lucide lucide-opps mt-0.5">&#xe94b;</span> <span>Potential Valuation Upside</span></p> </div> </div> <div> <h4 className="font-semibold text-gray-800 dark:text-gray-200 mb-3 border-b border-red-200 dark:border-red-700 pb-1">Risks</h4> <div className="space-y-3"> <p className="flex items-start text-sm text-red-800 dark:text-red-300"><span className="lucide lucide-risks mt-0.5">&#xe973;</span> <span>Regulatory & Political Changes</span></p> <p className="flex items-start text-sm text-red-800 dark:text-red-300"><span className="lucide lucide-risks mt-0.5">&#xea42;</span> <span>Geopolitical Tensions</span></p> <p className="flex items-start text-sm text-red-800 dark:text-red-300"><span className="lucide lucide-risks mt-0.5">&#xe987;</span> <span>Economic Imbalances (Property, Debt)</span></p> <p className="flex items-start text-sm text-red-800 dark:text-red-300"><span className="lucide lucide-risks mt-0.5">&#xe8c5;</span> <span>Market Volatility & Sentiment</span></p> </div> </div> </div> <div className="text-center mb-4"> <span className="inline-block bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300 text-xs font-semibold px-2.5 py-0.5 rounded-full border border-red-300 dark:border-red-600">Risk Level: High</span> </div> <p className="text-xs text-gray-500 dark:text-gray-400 text-center mb-4">Requires a long-term view and tolerance for significant fluctuations.</p> <p className="text-sm text-center"> <a href="#impl-china" className="inline-flex items-center text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 dark:hover:text-indigo-300 font-medium"> See Implementation Examples <span className="lucide ml-1 text-xs">&#xe8b0;</span> </a> </p> </div>
                 <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow border border-gray-200 dark:border-gray-700"> <h3 className="text-xl font-semibold mb-3 text-rose-700 dark:text-rose-400">Allocation Approaches (€100/month)</h3> <div className="space-y-4"> <div><h4 className="font-semibold text-gray-800 dark:text-gray-200">1. Balanced Approach:</h4><p className="text-gray-700 dark:text-gray-300 text-sm">Broad China/Asia ETF (e.g., MSCI China). Diversified.</p></div> <div><h4 className="font-semibold text-gray-800 dark:text-gray-200">2. High-Risk Approach:</h4><p className="text-gray-700 dark:text-gray-300 text-sm">Thematic ETF (e.g., Tech) or 1-2 Stocks (e.g., BABA, BYD). Concentrated.</p></div> <div> <h4 className="font-semibold text-gray-800 dark:text-gray-200">3. Combined Approach (Plan Suggestion):</h4> <p className="text-gray-700 dark:text-gray-300 text-sm">Split €100 (e.g., €50 Broad ETF + €50 Stock/Thematic). Balanced risk.</p> </div> </div> <div className="mt-6 p-4 bg-rose-50 dark:bg-rose-900/30 border border-rose-200 dark:border-rose-700/50 rounded-lg"> <p className="text-sm text-rose-800 dark:text-rose-300 font-medium flex items-center"><span className="lucide mr-2" style={{ fontSize: '1.25rem' }}></span> <strong>Important:</strong> Keep total China allocation capped (~17%). Invest only amounts you can afford potential large swings on.</p> </div> </div>
             </div>
        </section>
    );
}

export default ChinaSatelliteSection; 