import React from 'react';

function ImplementationSection() {
    // TODO: Add logic for highlighting cards based on chart clicks if needed
    return (
        <section id="implementation" className="mb-16 scroll-mt-16" data-aos="fade-up">
             <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-6 border-b pb-2 border-gray-300 dark:border-gray-600">Practical Implementation Guide</h2>
             <p className="text-gray-600 dark:text-gray-400 mb-6">Example ETFs and stocks for setting up your monthly investment plan (€600 total).</p>
             <div className="space-y-8">
                 <div>
                     <h3 className="text-xl font-semibold mb-4 text-indigo-700 dark:text-indigo-400">Core Portfolio (€500/month - ETFs)</h3>
                     <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                         <div id="impl-card-global" className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700 transition-all duration-200" data-aos="fade-up" data-aos-delay="100"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon text-indigo-600 dark:text-indigo-500 mr-1">&#xe976;</span> 1. Global Dev. ETF (€300)</h4> <a href="https://www.justetf.com/de/etf-profile.html?isin=IE00B4L5Y983" target="_blank" rel="noopener noreferrer" title="Open on JustETF" className="text-gray-400 dark:text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">iShares Core MSCI World UCITS ETF (Acc)</p> <p className="text-xs text-gray-500 dark:text-gray-400">ISIN: IE00B4L5Y983</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: ~0.20%</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Broad global diversification, low cost, accumulating.</p> </div>
                         <div id="impl-card-europe" className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700 transition-all duration-200" data-aos="fade-up" data-aos-delay="200"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon text-indigo-500 dark:text-indigo-400 mr-1">&#xe9a0;</span> 2. Europe ETF (€100)</h4> <a href="https://www.justetf.com/de/etf-profile.html?isin=DE0002635307" target="_blank" rel="noopener noreferrer" title="Open on JustETF" className="text-gray-400 dark:text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">iShares STOXX Europe 600 UCITS ETF (Acc)</p> <p className="text-xs text-gray-500 dark:text-gray-400">ISIN: DE0002635307</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: ~0.20%</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: European exposure, potential valuation, accumulating.</p> </div>
                         <div id="impl-card-em" className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700 transition-all duration-200" data-aos="fade-up" data-aos-delay="300"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon text-indigo-400 dark:text-indigo-300 mr-1">&#xe9c1;</span> 3. EM ETF (€100)</h4> <a href="https://www.justetf.com/de/etf-profile.html?isin=IE00BKM4GZ66" target="_blank" rel="noopener noreferrer" title="Open on JustETF" className="text-gray-400 dark:text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">iShares Core MSCI EM IMI UCITS ETF (Acc)</p> <p className="text-xs text-gray-500 dark:text-gray-400">ISIN: IE00BKM4GZ66</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: ~0.18%</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Higher growth potential, diversified emerging economies.</p> </div>
                     </div>
                     <h3 className="text-xl font-semibold mb-4 mt-6 text-indigo-700 dark:text-indigo-400">Optional Additions (within total €600 plan)</h3>
                      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                         <div className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700 opacity-75 dark:opacity-60" data-aos="fade-up" data-aos-delay="100"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon">&#xea37;</span> 4. Global Bond ETF (€50) (Optional)</h4> <a href="https://www.justetf.com/de/etf-profile.html?isin=IE00BDBRDM35" target="_blank" rel="noopener noreferrer" title="Open on JustETF" className="text-gray-400 dark:text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">iShares Global Agg Bond UCITS ETF (EUR Hedged)</p> <p className="text-xs text-gray-500 dark:text-gray-400">ISIN: IE00BDBRDM35</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: ~0.10%</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Adds stability, reduces volatility, EUR hedged.</p> </div>
                         <div className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700 opacity-75 dark:opacity-60" data-aos="fade-up" data-aos-delay="200"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon">&#xe9a2;</span> 5. Blue-Chip Stocks (€50) (Optional)</h4> <a href="https://www.google.com/finance/quote/MSFT:NASDAQ" target="_blank" rel="noopener noreferrer" title="Open on Google Finance" className="text-gray-400 dark:text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">e.g., Microsoft (US5949181045), Allianz (DE0008404005)</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: N/A</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Direct ownership in stable, global leaders (1-2 max).</p> </div>
                     </div>
                      <p className="text-sm text-gray-600 dark:text-gray-400 mt-4">Note: The core €500 is allocated to the three ETFs above. The optional €100 can be allocated to Bonds/Stocks instead of or alongside the China satellite, depending on preference.</p>
                 </div>
                 <div id="impl-china">
                     <h3 className="text-xl font-semibold mb-4 text-rose-700 dark:text-rose-400">China Satellite (€100/month)</h3>
                      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                         <div className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700" data-aos="fade-up" data-aos-delay="100"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon rose">&#xe8f4;</span> A. Broad China ETF (€50-€100)</h4> <a href="https://www.justetf.com/de/etf-profile.html?isin=LU0514695690" target="_blank" rel="noopener noreferrer" title="Open on JustETF" className="text-gray-400 dark:text-gray-500 hover:text-rose-600 dark:hover:text-rose-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Xtrackers MSCI China UCITS ETF (Acc)</p> <p className="text-xs text-gray-500 dark:text-gray-400">ISIN: LU0514695690</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: ~0.65%</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Diversified China exposure, balanced approach.</p> </div>
                         <div className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border border-gray-200 dark:border-gray-700" data-aos="fade-up" data-aos-delay="200"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon rose">&#xea6a;</span> B. High-Growth Stocks/ETF (€0-€50)</h4> <a href="https://www.justetf.com/de/etf-profile.html?isin=IE00BFXR7645" target="_blank" rel="noopener noreferrer" title="Open KWEB on JustETF" className="text-gray-400 dark:text-gray-500 hover:text-rose-600 dark:hover:text-rose-400"> <span className="lucide lucide-link">&#xe966;</span> </a> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">e.g., KWEB ETF (IE00BFXR7645), BABA, 700.HK, 1211.HK</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: Varies (ETF ~0.75%)</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Concentrated bets on specific growth themes/companies.</p> </div>
                         <div className="implementation-card bg-white dark:bg-gray-800 p-4 rounded-lg shadow border-2 border-rose-300 dark:border-rose-500" data-aos="fade-up" data-aos-delay="300"> <div> <div className="flex justify-between items-start mb-2"> <h4 className="font-semibold text-gray-800 dark:text-gray-200 flex items-center"><span className="lucide lucide-card-icon rose">&#xe8e5;</span> C. Combined Approach (Plan Suggestion)</h4> </div> <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">€50 Broad China ETF + €50 split on 1-2 Stocks/Thematic ETF</p> <p className="text-xs text-gray-500 dark:text-gray-400">ISIN: Mix</p> <p className="text-xs text-gray-500 dark:text-gray-400">TER: Mix</p> </div> <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">Why: Balances diversification with targeted growth potential.</p> </div>
                      </div>
                 </div>
             </div>

             <div className="mt-8 p-4 bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-700/50 rounded-lg" data-aos="fade-up">
                 <h4 className="font-semibold text-lg text-blue-800 dark:text-blue-300 mb-3 flex items-center">
                     <span className="lucide mr-2" style={{ fontSize: '1.1rem' }}>&#xea4c;</span> Choosing Your Broker
                 </h4>
                 <p className="text-sm text-blue-700 dark:text-blue-400 mb-3">Selecting the right broker is crucial for efficient implementation. Key factors for German investors include:</p>
                 <ul className="list-disc list-inside space-y-1 text-sm text-blue-700 dark:text-blue-400 pl-4">
                     <li><strong>Low-cost Sparpläne:</strong> Availability and fees for automated ETF/Stock savings plans.</li>
                     <li><strong>Asset Availability:</strong> Ensure the broker offers the specific ETFs and stocks you plan to invest in.</li>
                     <li><strong>User Interface:</strong> Ease of use of the web platform and mobile app.</li>
                     <li><strong>Security:</strong> Features like two-factor authentication (2FA) and deposit protection schemes.</li>
                     <li><strong>Tax Reporting:</strong> Simplified tax handling, ideally with automatic generation of the German tax certificate (<em>Steuerbescheinigung</em>).</li>
                 </ul>
                 <p className="text-xs text-blue-600 dark:text-blue-500 mt-3">Popular brokers in Germany include names like Scalable Capital, Trade Republic, ING, Consorsbank, and others. Compare their current conditions and features.</p>
             </div>

              <p className="text-sm text-gray-600 dark:text-gray-400 mt-6" data-aos="fade-up">Use a broker offering Sparpläne (savings plans) for automated monthly investments, often available for ETFs and major stocks (e.g., Scalable Capital, Trade Republic in Germany).</p>
        </section>
    );
}

export default ImplementationSection; 